baseURL = 'https://dry-han.github.io/stage-bloggy'
languageCode = 'en-us'
title = 'Stage Bloggy'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  linkTitle = 'SuperDuck'
  disableLandingPageButton = true
  showVisitedLinks = true
  alwaysopen = false
  collapsibleMenu = true
  [params.search]
    disable = true
    [params.search.index]
      disable = true
    [params.search.page]
      disable = true
  themeVariant = [ 'relearn-dark']