baseURL = 'https://panaview.github.io/bloggy'
languageCode = 'en-us'
title = 'Bloggy!'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  linkTitle = 'Bloggy!'
  disableLandingPageButton = true
  showVisitedLinks = true
  alwaysopen = false
  themeVariant = 'relearn-dark'
  collapsibleMenu = true
  [params.search]
    disable = true
    [params.search.index]
      disable = true
    [params.search.page]
      disable = true